// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: api/proto/pricefeed/pricefeed.proto

package pricefeed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceFeed_SubscribePrices_FullMethodName = "/pricefeed.PriceFeed/SubscribePrices"
)

// PriceFeedClient is the client API for PriceFeed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceFeedClient interface {
	SubscribePrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceSnapshotList], error)
}

type priceFeedClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceFeedClient(cc grpc.ClientConnInterface) PriceFeedClient {
	return &priceFeedClient{cc}
}

func (c *priceFeedClient) SubscribePrices(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceSnapshotList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceFeed_ServiceDesc.Streams[0], PriceFeed_SubscribePrices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PriceRequest, PriceSnapshotList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceFeed_SubscribePricesClient = grpc.ServerStreamingClient[PriceSnapshotList]

// PriceFeedServer is the server API for PriceFeed service.
// All implementations must embed UnimplementedPriceFeedServer
// for forward compatibility.
type PriceFeedServer interface {
	SubscribePrices(*PriceRequest, grpc.ServerStreamingServer[PriceSnapshotList]) error
	mustEmbedUnimplementedPriceFeedServer()
}

// UnimplementedPriceFeedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceFeedServer struct{}

func (UnimplementedPriceFeedServer) SubscribePrices(*PriceRequest, grpc.ServerStreamingServer[PriceSnapshotList]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePrices not implemented")
}
func (UnimplementedPriceFeedServer) mustEmbedUnimplementedPriceFeedServer() {}
func (UnimplementedPriceFeedServer) testEmbeddedByValue()                   {}

// UnsafePriceFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceFeedServer will
// result in compilation errors.
type UnsafePriceFeedServer interface {
	mustEmbedUnimplementedPriceFeedServer()
}

func RegisterPriceFeedServer(s grpc.ServiceRegistrar, srv PriceFeedServer) {
	// If the following call pancis, it indicates UnimplementedPriceFeedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceFeed_ServiceDesc, srv)
}

func _PriceFeed_SubscribePrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PriceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceFeedServer).SubscribePrices(m, &grpc.GenericServerStream[PriceRequest, PriceSnapshotList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceFeed_SubscribePricesServer = grpc.ServerStreamingServer[PriceSnapshotList]

// PriceFeed_ServiceDesc is the grpc.ServiceDesc for PriceFeed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceFeed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricefeed.PriceFeed",
	HandlerType: (*PriceFeedServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePrices",
			Handler:       _PriceFeed_SubscribePrices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/pricefeed/pricefeed.proto",
}
