// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: api/proto/pricefeed/pricefeed.proto

package pricefeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_api_proto_pricefeed_pricefeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricefeed_pricefeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricefeed_pricefeed_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type PriceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceSnapshot) Reset() {
	*x = PriceSnapshot{}
	mi := &file_api_proto_pricefeed_pricefeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceSnapshot) ProtoMessage() {}

func (x *PriceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricefeed_pricefeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceSnapshot.ProtoReflect.Descriptor instead.
func (*PriceSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_pricefeed_pricefeed_proto_rawDescGZIP(), []int{1}
}

func (x *PriceSnapshot) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *PriceSnapshot) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceSnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_pricefeed_pricefeed_proto protoreflect.FileDescriptor

const file_api_proto_pricefeed_pricefeed_proto_rawDesc = "" +
	"\n" +
	"#api/proto/pricefeed/pricefeed.proto\x12\tpricefeed\"\"\n" +
	"\fPriceRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"W\n" +
	"\rPriceSnapshot\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2S\n" +
	"\tPriceFeed\x12F\n" +
	"\x0fSubscribePrices\x12\x17.pricefeed.PriceRequest\x1a\x18.pricefeed.PriceSnapshot0\x01B2Z0github.com/chiyonn/swarmyard/api/proto/pricefeedb\x06proto3"

var (
	file_api_proto_pricefeed_pricefeed_proto_rawDescOnce sync.Once
	file_api_proto_pricefeed_pricefeed_proto_rawDescData []byte
)

func file_api_proto_pricefeed_pricefeed_proto_rawDescGZIP() []byte {
	file_api_proto_pricefeed_pricefeed_proto_rawDescOnce.Do(func() {
		file_api_proto_pricefeed_pricefeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pricefeed_pricefeed_proto_rawDesc), len(file_api_proto_pricefeed_pricefeed_proto_rawDesc)))
	})
	return file_api_proto_pricefeed_pricefeed_proto_rawDescData
}

var file_api_proto_pricefeed_pricefeed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_pricefeed_pricefeed_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: pricefeed.PriceRequest
	(*PriceSnapshot)(nil), // 1: pricefeed.PriceSnapshot
}
var file_api_proto_pricefeed_pricefeed_proto_depIdxs = []int32{
	0, // 0: pricefeed.PriceFeed.SubscribePrices:input_type -> pricefeed.PriceRequest
	1, // 1: pricefeed.PriceFeed.SubscribePrices:output_type -> pricefeed.PriceSnapshot
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_pricefeed_pricefeed_proto_init() }
func file_api_proto_pricefeed_pricefeed_proto_init() {
	if File_api_proto_pricefeed_pricefeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pricefeed_pricefeed_proto_rawDesc), len(file_api_proto_pricefeed_pricefeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pricefeed_pricefeed_proto_goTypes,
		DependencyIndexes: file_api_proto_pricefeed_pricefeed_proto_depIdxs,
		MessageInfos:      file_api_proto_pricefeed_pricefeed_proto_msgTypes,
	}.Build()
	File_api_proto_pricefeed_pricefeed_proto = out.File
	file_api_proto_pricefeed_pricefeed_proto_goTypes = nil
	file_api_proto_pricefeed_pricefeed_proto_depIdxs = nil
}
