services:
  executor:
    build:
      context: ../
      dockerfile: apps/executor/Dockerfile
    env_file:
      - .env.global
      - .env.executor
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ../:/app
    working_dir: /app/apps/executor

  pricefeed:
    build:
      context: ../
      dockerfile: apps/pricefeed/Dockerfile
    env_file:
      - .env.global
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ../:/app
    working_dir: /app/apps/pricefeed

  aggregator:
    build:
      context: ../
      dockerfile: apps/aggregator/Dockerfile
    env_file:
      - .env.global
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ../:/app
    working_dir: /app/apps/aggregator

  bot-sma:
    build:
      context: ../
      dockerfile: apps/bot-sma/Dockerfile
    env_file:
      - .env.global
      - .env.bot-sma
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ../:/app
    working_dir: /app/apps/bot-sma
    depends_on:
      - executor
      - pricefeed

  dashboard:
    build:
      context: ../
      dockerfile: apps/dashboard/Dockerfile
    env_file:
      - .env.global
      - .env.bashboard
    command: ["yarn", "dev"]
    ports:
      - "3000:5173"
    volumes:
      - ../:/app
    working_dir: /app/apps/dashboard
