services:
  executor:
    build:
      context: ../
      dockerfile: apps/executor/Dockerfile
    env_file:
      - .env.global
      - .env.executor

  aggregator:
    build:
      context: ../
      dockerfile: apps/aggregator/Dockerfile
    env_file:
      - .env.global

  bot-sma:
    build:
      context: ../
      dockerfile: apps/bot-sma/Dockerfile
    env_file:
      - .env.global
      - .env.bot-sma

  dashboard:
    build:
      context: ../
      dockerfile: apps/dashboard/Dockerfile

