// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/tradeexecutor/tradeexecutor.proto

package tradeexecutor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *OrderRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *OrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         string                 `protobuf:"bytes,1,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotRequest) Reset() {
	*x = BotRequest{}
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotRequest) ProtoMessage() {}

func (x *BotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotRequest.ProtoReflect.Descriptor instead.
func (*BotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescGZIP(), []int{2}
}

func (x *BotRequest) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

type BotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotResponse) Reset() {
	*x = BotResponse{}
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotResponse) ProtoMessage() {}

func (x *BotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotResponse.ProtoReflect.Descriptor instead.
func (*BotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescGZIP(), []int{3}
}

func (x *BotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_tradeexecutor_tradeexecutor_proto protoreflect.FileDescriptor

const file_api_proto_tradeexecutor_tradeexecutor_proto_rawDesc = "" +
	"\n" +
	"+api/proto/tradeexecutor/tradeexecutor.proto\x12\rtradeexecutor\"Q\n" +
	"\fOrderRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"B\n" +
	"\rOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"#\n" +
	"\n" +
	"BotRequest\x12\x15\n" +
	"\x06bot_id\x18\x01 \x01(\tR\x05botId\"%\n" +
	"\vBotResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xdf\x01\n" +
	"\rTradeExecutor\x12G\n" +
	"\n" +
	"PlaceOrder\x12\x1b.tradeexecutor.OrderRequest\x1a\x1c.tradeexecutor.OrderResponse\x12A\n" +
	"\bPauseBot\x12\x19.tradeexecutor.BotRequest\x1a\x1a.tradeexecutor.BotResponse\x12B\n" +
	"\tResumeBot\x12\x19.tradeexecutor.BotRequest\x1a\x1a.tradeexecutor.BotResponseB6Z4github.com/example/swarmyard/api/proto/tradeexecutorb\x06proto3"

var (
	file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescOnce sync.Once
	file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescData []byte
)

func file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescGZIP() []byte {
	file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescOnce.Do(func() {
		file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tradeexecutor_tradeexecutor_proto_rawDesc), len(file_api_proto_tradeexecutor_tradeexecutor_proto_rawDesc)))
	})
	return file_api_proto_tradeexecutor_tradeexecutor_proto_rawDescData
}

var file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_tradeexecutor_tradeexecutor_proto_goTypes = []any{
	(*OrderRequest)(nil),  // 0: tradeexecutor.OrderRequest
	(*OrderResponse)(nil), // 1: tradeexecutor.OrderResponse
	(*BotRequest)(nil),    // 2: tradeexecutor.BotRequest
	(*BotResponse)(nil),   // 3: tradeexecutor.BotResponse
}
var file_api_proto_tradeexecutor_tradeexecutor_proto_depIdxs = []int32{
	0, // 0: tradeexecutor.TradeExecutor.PlaceOrder:input_type -> tradeexecutor.OrderRequest
	2, // 1: tradeexecutor.TradeExecutor.PauseBot:input_type -> tradeexecutor.BotRequest
	2, // 2: tradeexecutor.TradeExecutor.ResumeBot:input_type -> tradeexecutor.BotRequest
	1, // 3: tradeexecutor.TradeExecutor.PlaceOrder:output_type -> tradeexecutor.OrderResponse
	3, // 4: tradeexecutor.TradeExecutor.PauseBot:output_type -> tradeexecutor.BotResponse
	3, // 5: tradeexecutor.TradeExecutor.ResumeBot:output_type -> tradeexecutor.BotResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_tradeexecutor_tradeexecutor_proto_init() }
func file_api_proto_tradeexecutor_tradeexecutor_proto_init() {
	if File_api_proto_tradeexecutor_tradeexecutor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tradeexecutor_tradeexecutor_proto_rawDesc), len(file_api_proto_tradeexecutor_tradeexecutor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tradeexecutor_tradeexecutor_proto_goTypes,
		DependencyIndexes: file_api_proto_tradeexecutor_tradeexecutor_proto_depIdxs,
		MessageInfos:      file_api_proto_tradeexecutor_tradeexecutor_proto_msgTypes,
	}.Build()
	File_api_proto_tradeexecutor_tradeexecutor_proto = out.File
	file_api_proto_tradeexecutor_tradeexecutor_proto_goTypes = nil
	file_api_proto_tradeexecutor_tradeexecutor_proto_depIdxs = nil
}
